### ISSUE TITLE
lw5

### ISSUE THREAD

**Issue by panda-andreevna** [Kirill20Egorov/web-development#1]
- [x] структура проекта нарушена (style.css)
- [x] картинки названы неверно
- [x] "321" кометы необходимо расписывать
- [x] если текст доходит до середины экрана, его необходимо переносить
- [x] у label неверно записан атрибут for
- [x] классы где-то названы через дефис где-то через нижнее подчеркивание
- [x] по значению "OUR ADRESS" и остальные не h2
- [x] верстка поехала https://ibb.co/myYDmrm
- [x] между стилями необходимо оставлять пустую строку
- [x] нет альтернативных шрифтов
- [x] нет загрузки шрифтов
- [x] нет css-файла "стерки"
- [x] свойства font пишем в одну строку http://htmlbook.ru/css/font
- [x] yak в переводе с английского бык, вредил вы это имели ввиду, когда картинке якоря присваивали этот класс (пересмотреть названия классов)

**Comment by panda-andreevna** [comment]
чекбоксы проставляет преподаватель.
исправлено не все.

**Comment by Kirill20Egorov** [comment]
> чекбоксы проставляет преподаватель.
> исправлено не все.

А что делать с таблицей баллов за 5.1? Просто у тех ребят, кто с Инфотеха и сдавал эту страничку, это задание оценивалось как 5.2, а за 5.1 баллы видимо просто так шли, как я спросил. Ну и можете сами по табличке глянуть у ПС-13 например)
У меня сжимается везде где есть текст теперь сжимается, сделал таким образом:
![image](https://user-images.githubusercontent.com/37872861/78263421-99e0f100-750a-11ea-94ab-35353d0c5387.png)
![image](https://user-images.githubusercontent.com/37872861/78263509-ba10b000-750a-11ea-8b0a-944221714fec.png)
![image](https://user-images.githubusercontent.com/37872861/78263571-ce54ad00-750a-11ea-96df-f332da39ff07.png)
![image](https://user-images.githubusercontent.com/37872861/78263630-e2001380-750a-11ea-90df-9a783754ea6b.png)
![image](https://user-images.githubusercontent.com/37872861/78263687-f80dd400-750a-11ea-8ea8-5e5526bfa80b.png)
![image](https://user-images.githubusercontent.com/37872861/78263744-08be4a00-750b-11ea-9a6f-b66bfdd07ac2.png)
Кто будет при 200px смотреть эту страничку?
![image](https://user-images.githubusercontent.com/37872861/78263827-1a9fed00-750b-11ea-9cbc-dbc8d3a71a53.png)
![image](https://user-images.githubusercontent.com/37872861/78263931-3dca9c80-750b-11ea-9f38-1a2e5cce1fc4.png)
![image](https://user-images.githubusercontent.com/37872861/78263984-4b802200-750b-11ea-9694-7374747ddac7.png)

**Comment by panda-andreevna** [comment]
текст в файле index.html, а картинки в одном стиле должны быть названы
5.1 и 5.2 проставлю за эту лабу

**Comment by Kirill20Egorov** [comment]
> текст в файле index.html, а картинки в одном стиле должны быть названы
> 5.1 и 5.2 проставлю за эту лабу

я не понимаю, картинки одним стилем названы, это имеете в виду с маленькой буквы например все или что? 
+ у меня ведь сжимается уже всё? покажите, где не сжимается, и до 200px сжимал всё, спрашивал у ребят, кто сдавал этот пост, у них елена кузнецова принимала, им до 1366px минимально верстку проверяли. но у меня ведь вообще всё сжимается уже?

**Comment by Kirill20Egorov** [comment]
> текст в файле index.html, а картинки в одном стиле должны быть названы
> 5.1 и 5.2 проставлю за эту лабу

1) Я не понимаю, картинки одним стилем названы, это имеете в виду с маленькой буквы например все или что? Вроде как по названиям картинки смысл несут)

У меня ведь текст везде уже переходит? Покажите, где не переходит текст, и до минимальных размеров сжимал всё, но у меня ведь при сжатии текст переносится, нет разве? 
Это конечно не адаптивность у меня, но мы вроде как медиа-запросы не изучали еще, да и по заданию адаптивности не было на эту страничку, вот.

А еще уточните пожалуйста вопрос про 5.1 с Еленой Кузнецовой, просто у ребят, кто сдавал эту страничку "Welcome to Bino" у них за 5.1 стоит коэффициент 1, а эта работа шла только за 5.2
